  #ifndef FAUNA_CREDENTIALS_h
  #define FAUNA_CREDENTIALS_h
  //
  // Automatically generated by fauna_example_config.rb
  //

  #define FAUNA_PUBLISHER_KEY @"AQAAZ1LeD5AAAABnUt3tcAAAwK5dYxtjTuiZsucrHk73Tg"
  #define FAUNA_CLIENT_KEY @"AQEAZ1LeKiAAAABnUt3tcAAAaq23JT3j_tbYXWavXgoQzA"

  #endif
