//
// FaunaCredentials.h
//
// Copyright (c) 2013 Fauna, Inc.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License. You may obtain a
// copy of the License at
//
// http://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software distributed
// under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//
  #ifndef FAUNA_CREDENTIALS_h
  #define FAUNA_CREDENTIALS_h
  //
  // Automatically generated by fauna_example_config.rb
  //

  #define FAUNA_PUBLISHER_KEY @"AQAAZGvPEpAAAABka87wsAAAB2_nRv0apsP1JGT0CHsLmA"
  #define FAUNA_CLIENT_KEY @"AQEAZGvPLaAAAABka87wsAAA5c9lDMhF-x6JPMcwKyEq6g"

  #endif
