  #ifndef FAUNA_CREDENTIALS_h
  #define FAUNA_CREDENTIALS_h
  //
  // Automatically generated by fauna_example_config.rb
  //

  #define FAUNA_PUBLISHER_KEY @"AQAAZGvPEpAAAABka87wsAAAB2_nRv0apsP1JGT0CHsLmA"
  #define FAUNA_CLIENT_KEY @"AQEAZGvPLaAAAABka87wsAAA5c9lDMhF-x6JPMcwKyEq6g"

  #endif
